matrix:
  include:
    - language: python
      python: 3.7
      before_install:
        - cd scripts
      install:
        - pip install -r requirements.txt
      script:
        - python run_polly.py www.cycif.org
    - language: ruby
      install:
        - gem install jekyll bundler
        - bundle install
        - npm install
        - npm install webpack
        - npm install webpack-cli
      script: 
        - ./node_modules/.bin/webpack --mode production
        - bundle exec jekyll build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: false
        local_dir: _site
        on:
          branch: master
